name: Locations
version: 1.0
description: 
author: leee leee
website: denmc.online

main: org.Locations.Locations

commands:
    locations:
        description: Leeeleee's Locations
        permission: leeeleees.locs
        usage: /<command> help
    locs:
        description: Leeeleee's Locations
        permission: leeeleees.locs
        usage: /<command> help


permissions: {}
